# Generated by Django 5.2 on 2025-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaOperativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaoperativo',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_so/'),
        ),
    ]
