# Generated by Django 5.2 on 2025-06-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SistemaOperativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('fotoe', models.FileField(upload_to='equipos')),
                ('fichatec', models.FileField(upload_to='equipos')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaOperativo.sistemaoperativo')),
            ],
        ),
    ]
